apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

images:
- name: forfog/nginx
  newTag: kastomize

labels:
- includeSelectors: true
  pairs:
    app: deploy-kustomize

patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: kustomize
    - op: replace
      path: /spec/ports/0/port
      value: 83
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30003
  target:
    kind: Service
- patch: |-
    - op: replace
      path: /metadata/name
      value: kustomize
    - op: replace
      path: /spec/template/spec/containers/0/name
      value: kustomize
  target:
    kind: Deployment
